import type { StampDefinition } from '../models/stamp'

export const STAMP_DEFINITIONS: StampDefinition[] = [
  // 汎用スタンプ
  {
    id: 'gen_warning',
    category: '汎用',
    label: '注意',
    defaultText: '注意',
    defaultStyle: { backgroundColor: '#ff9800', textColor: '#ffffff' },
  },
  {
    id: 'gen_danger',
    category: '汎用',
    label: '危険',
    defaultText: '危険',
    defaultStyle: { backgroundColor: '#f44336', textColor: '#ffffff' },
  },
  {
    id: 'gen_ok',
    category: '汎用',
    label: 'OK',
    defaultText: 'OK',
    defaultStyle: { backgroundColor: '#4caf50', textColor: '#ffffff' },
  },
  {
    id: 'gen_ng',
    category: '汎用',
    label: 'NG',
    defaultText: 'NG',
    defaultStyle: { backgroundColor: '#f44336', textColor: '#ffffff' },
  },
  {
    id: 'gen_move',
    category: '汎用',
    label: '移動',
    defaultText: '移動',
    defaultStyle: { backgroundColor: '#2196f3', textColor: '#ffffff' },
  },
  {
    id: 'gen_stop',
    category: '汎用',
    label: '停止',
    defaultText: '停止',
    defaultStyle: { backgroundColor: '#9e9e9e', textColor: '#ffffff' },
  },
  {
    id: 'gen_gather',
    category: '汎用',
    label: '集合',
    defaultText: '集合',
    defaultStyle: { backgroundColor: '#ffc107', textColor: '#000000' },
  },
  {
    id: 'gen_away',
    category: '汎用',
    label: '離れる',
    defaultText: '離れる',
    defaultStyle: { backgroundColor: '#9c27b0', textColor: '#ffffff' },
  },
  {
    id: 'gen_self',
    category: '汎用',
    label: '自分',
    defaultText: '自分',
    defaultStyle: { backgroundColor: '#00bcd4', textColor: '#ffffff' },
  },
  {
    id: 'gen_target',
    category: '汎用',
    label: '目標',
    defaultText: '目標',
    defaultStyle: { backgroundColor: '#e91e63', textColor: '#ffffff' },
  },
  {
    id: 'gen_1st',
    category: '汎用',
    label: '1回目',
    defaultText: '1',
    defaultStyle: { backgroundColor: '#3f51b5', textColor: '#ffffff' },
  },
  {
    id: 'gen_2nd',
    category: '汎用',
    label: '2回目',
    defaultText: '2',
    defaultStyle: { backgroundColor: '#3f51b5', textColor: '#ffffff' },
  },
  {
    id: 'gen_3rd',
    category: '汎用',
    label: '3回目',
    defaultText: '3',
    defaultStyle: { backgroundColor: '#3f51b5', textColor: '#ffffff' },
  },
  {
    id: 'gen_4th',
    category: '汎用',
    label: '4回目',
    defaultText: '4',
    defaultStyle: { backgroundColor: '#3f51b5', textColor: '#ffffff' },
  },
  {
    id: 'gen_north',
    category: '汎用',
    label: '北',
    defaultText: '北',
    defaultStyle: { backgroundColor: '#607d8b', textColor: '#ffffff' },
  },
  {
    id: 'gen_south',
    category: '汎用',
    label: '南',
    defaultText: '南',
    defaultStyle: { backgroundColor: '#607d8b', textColor: '#ffffff' },
  },
  {
    id: 'gen_east',
    category: '汎用',
    label: '東',
    defaultText: '東',
    defaultStyle: { backgroundColor: '#607d8b', textColor: '#ffffff' },
  },
  {
    id: 'gen_west',
    category: '汎用',
    label: '西',
    defaultText: '西',
    defaultStyle: { backgroundColor: '#607d8b', textColor: '#ffffff' },
  },
  {
    id: 'gen_cw',
    category: '汎用',
    label: '時計回り',
    defaultText: '時計回り',
    defaultStyle: { backgroundColor: '#009688', textColor: '#ffffff' },
  },
  {
    id: 'gen_ccw',
    category: '汎用',
    label: '反時計回り',
    defaultText: '反時計回り',
    defaultStyle: { backgroundColor: '#009688', textColor: '#ffffff' },
  },

  // FF14向けスタンプ
  {
    id: 'ff14_spread',
    category: 'FF14',
    label: '散開',
    defaultText: '散開',
    defaultStyle: { backgroundColor: '#8bc34a', textColor: '#000000' },
  },
  {
    id: 'ff14_stack',
    category: 'FF14',
    label: '頭割り',
    defaultText: '頭割り',
    defaultStyle: { backgroundColor: '#ffeb3b', textColor: '#000000' },
  },
  {
    id: 'ff14_tank',
    category: 'FF14',
    label: 'タンク',
    defaultText: 'Tank',
    defaultStyle: { backgroundColor: '#2196f3', textColor: '#ffffff' },
  },
  {
    id: 'ff14_healer',
    category: 'FF14',
    label: 'ヒーラー',
    defaultText: 'Healer',
    defaultStyle: { backgroundColor: '#4caf50', textColor: '#ffffff' },
  },
  {
    id: 'ff14_dps',
    category: 'FF14',
    label: 'DPS',
    defaultText: 'DPS',
    defaultStyle: { backgroundColor: '#f44336', textColor: '#ffffff' },
  },
  {
    id: 'ff14_mt',
    category: 'FF14',
    label: 'MT',
    defaultText: 'MT',
    defaultStyle: { backgroundColor: '#1976d2', textColor: '#ffffff' },
  },
  {
    id: 'ff14_st',
    category: 'FF14',
    label: 'ST',
    defaultText: 'ST',
    defaultStyle: { backgroundColor: '#64b5f6', textColor: '#000000' },
  },
  {
    id: 'ff14_h1',
    category: 'FF14',
    label: 'H1',
    defaultText: 'H1',
    defaultStyle: { backgroundColor: '#388e3c', textColor: '#ffffff' },
  },
  {
    id: 'ff14_h2',
    category: 'FF14',
    label: 'H2',
    defaultText: 'H2',
    defaultStyle: { backgroundColor: '#81c784', textColor: '#000000' },
  },
  {
    id: 'ff14_d1',
    category: 'FF14',
    label: 'D1',
    defaultText: 'D1',
    defaultStyle: { backgroundColor: '#d32f2f', textColor: '#ffffff' },
  },
  {
    id: 'ff14_d2',
    category: 'FF14',
    label: 'D2',
    defaultText: 'D2',
    defaultStyle: { backgroundColor: '#e57373', textColor: '#000000' },
  },
  {
    id: 'ff14_d3',
    category: 'FF14',
    label: 'D3',
    defaultText: 'D3',
    defaultStyle: { backgroundColor: '#d32f2f', textColor: '#ffffff' },
  },
  {
    id: 'ff14_d4',
    category: 'FF14',
    label: 'D4',
    defaultText: 'D4',
    defaultStyle: { backgroundColor: '#e57373', textColor: '#000000' },
  },
  {
    id: 'ff14_mark_a',
    category: 'FF14',
    label: 'A',
    defaultText: 'A',
    defaultStyle: { backgroundColor: '#f44336', textColor: '#ffffff', borderColor: '#ffffff' },
  },
  {
    id: 'ff14_mark_b',
    category: 'FF14',
    label: 'B',
    defaultText: 'B',
    defaultStyle: { backgroundColor: '#ffeb3b', textColor: '#000000', borderColor: '#ffffff' },
  },
  {
    id: 'ff14_mark_c',
    category: 'FF14',
    label: 'C',
    defaultText: 'C',
    defaultStyle: { backgroundColor: '#2196f3', textColor: '#ffffff', borderColor: '#ffffff' },
  },
  {
    id: 'ff14_mark_d',
    category: 'FF14',
    label: 'D',
    defaultText: 'D',
    defaultStyle: { backgroundColor: '#9c27b0', textColor: '#ffffff', borderColor: '#ffffff' },
  },
  {
    id: 'ff14_mark_1',
    category: 'FF14',
    label: '1',
    defaultText: '1',
    defaultStyle: { backgroundColor: '#f44336', textColor: '#ffffff', borderColor: '#ffffff' },
  },
  {
    id: 'ff14_mark_2',
    category: 'FF14',
    label: '2',
    defaultText: '2',
    defaultStyle: { backgroundColor: '#ffeb3b', textColor: '#000000', borderColor: '#ffffff' },
  },
  {
    id: 'ff14_mark_3',
    category: 'FF14',
    label: '3',
    defaultText: '3',
    defaultStyle: { backgroundColor: '#2196f3', textColor: '#ffffff', borderColor: '#ffffff' },
  },
  {
    id: 'ff14_mark_4',
    category: 'FF14',
    label: '4',
    defaultText: '4',
    defaultStyle: { backgroundColor: '#9c27b0', textColor: '#ffffff', borderColor: '#ffffff' },
  },
  {
    id: 'ff14_mark_5',
    category: 'FF14',
    label: '5',
    defaultText: '5',
    defaultStyle: { backgroundColor: '#ff9800', textColor: '#ffffff', borderColor: '#ffffff' },
  },
  {
    id: 'ff14_mark_6',
    category: 'FF14',
    label: '6',
    defaultText: '6',
    defaultStyle: { backgroundColor: '#ff9800', textColor: '#ffffff', borderColor: '#ffffff' },
  },
  {
    id: 'ff14_mark_7',
    category: 'FF14',
    label: '7',
    defaultText: '7',
    defaultStyle: { backgroundColor: '#ff9800', textColor: '#ffffff', borderColor: '#ffffff' },
  },
  {
    id: 'ff14_mark_8',
    category: 'FF14',
    label: '8',
    defaultText: '8',
    defaultStyle: { backgroundColor: '#ff9800', textColor: '#ffffff', borderColor: '#ffffff' },
  },
  {
    id: 'ff14_outer',
    category: 'FF14',
    label: '外周',
    defaultText: '外周',
    defaultStyle: { backgroundColor: '#795548', textColor: '#ffffff' },
  },
  {
    id: 'ff14_center',
    category: 'FF14',
    label: '中央',
    defaultText: '中央',
    defaultStyle: { backgroundColor: '#795548', textColor: '#ffffff' },
  },
  {
    id: 'ff14_bait',
    category: 'FF14',
    label: '誘導',
    defaultText: '誘導',
    defaultStyle: { backgroundColor: '#e91e63', textColor: '#ffffff' },
  },
  {
    id: 'ff14_mitigate',
    category: 'FF14',
    label: '軽減',
    defaultText: '軽減',
    defaultStyle: { backgroundColor: '#8bc34a', textColor: '#000000' },
  },
]
